spring:
  datasource:
    url: jdbc:h2:mem:blogdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    org.hibernate.SQL: warn

app:
  jwt:
    secret: "change_me_to_a_long_random_secret_please_1234567890"
    expiration-ms: 86400000
